---
title: "develop"
output: pdf_document
---

```{r setup, echo = FALSE, message=FALSE, warning=FALSE}
library(here)
library(wesanderson)
library(haven)

library(tidyverse)
library(ggpubr)

library(car)
library(glmnet)

source(here("R", "data.R"))
source(here("R", "plot.R"))
```


```{r data}
year <- 2019

data <- load_data(year)

var_considered <- preselect_variables(data)


# write_csv(data.frame(ques = unlist(selected_questions)), here("data", paste0("selected_questions.csv")))
```



``` {r}
reverse_order <- c("QI1_agtfun", "QI1_aglerwan", "QI1_aglereasy", "QR4_s_agptime", "QI8_agremv", "QI8_agwtime", "QI8_agttime")
exclude <- c("QN2_u_actcom", "QN3_u_actpay", "QD1_yrborn", "QO6E_Gradec", "QL1_dgorig")

value_maps <- list(QP3 = c("2" = 1, "3" = 2))

covars <- preprocess_covars(data, var_considered, reverse_order, exclude, value_maps)
outcome.data <- preprocess_outcomes(data, var_considered)


```

``` {r}
colSums(is.na(outcome.data)) / NROW(outcome.data)
sum(rowSums(is.na(outcome.data)) > 0) / NROW(outcome.data)

proc_res <- preprocess_data(covars$covars.data, outcome.data, covars$weights)
covars.data <- as.data.frame(proc_res$covars.data)
outcome.data <- as.data.frame(proc_res$outcome.data)
weights <- proc_res$weights

proxies <- show_proxies(covars.data)

# covars.data <- covars.data %>% select(-QS2_s_wheng.NA)
```

``` {r}
covarx_explore <- c("QC23", "QO4E_grader")
plot.data <- data.frame(covar = NULL, covar_name = NULL,
                        outcome = NULL, outcome_name = NULL)
for(covar_explore in covarx_explore){
  plot.data <- rbind(plot.data, data.frame(covar = covars.data[[covar_explore]],
                                           covar_name = covar_explore,
                                           outcome = outcome.data[, 1],
                                           outcome_name = "Concern"))
  plot.data <- rbind(plot.data, data.frame(covar = covars.data[[covar_explore]],
                                           covar_name = covar_explore,
                                           outcome = outcome.data[, 2],
                                           outcome_name = "Action"))
}

ggplot(plot.data, aes(x = covar, y = outcome)) +
  geom_point(alpha = 0.1 * rep(weights, 4), shape = 16) +
  facet_grid(covar_name ~ outcome_name) +
  ylim(-1.5, 1.5) +
  theme_bw()

# ggsave(here("figs", "explore_relation.pdf"), height = 5, width = 5)
```


``` {r}

demo_questions <- c("QD1_yrborn2", "QD2_gender", "QD14_ethnic",
                    "QD4_adulthh", "QD5_childhh", "QD3_marstat",
                    "QD16_disab", "QD18_urbrur",
                    "QL2_Edntt", "QO1_Labfor", "QO4E_grader", "Q1_income")
outcomes <- c("QR3_s_frpriv3", "QN1_u_concom", "QB1_agcred", "QB1_agprov", "QB1_agpdat",
              "QC12.*", "QC41_u_ad", "QC43.*", "QC42_u_pprot")

demo_data <- data$raw_data[c(demo_questions, "weight")]
write_csv(demo_data, here("data", "temp.csv"))
demo_data <- read_csv(here("data", "temp.csv"))


demo_answers <- data$answers[demo_questions]
names(demo_answers[["QD3_marstat"]])[c(4, 5)] <- c("Partner", "Divorced")
names(demo_answers[["QD18_urbrur"]])[c(3:7)] <- c("Big city", "Suburbs", "Town", "Village", "Farm")
names(demo_answers[["QL2_Edntt"]]) <- c("Primary school", "Secondary school", "Special school", "Sixth form college", "Technical college", "Further Education College", "Adult Community College", "University", "Other")
names(demo_answers[["QO1_Labfor"]])[c(2, 3, 6, 7, 12)] <- c("Full time", "Part time", "Disabled", "Community service", "Housework")
names(demo_answers[["Q1_income"]])[2:10] <- c("0-12.5", "12.5-20", "20-30", "30-40", "40-50", "50-60", "60-70", "70-80", "80+")

demo_names <- c("Age", "Gender", "Ethnics", "#Household Adults", "#Household Children",
                "Marital Status", "disabled?", "Place of Residence", "Education",
                "Employment", "NRS Social Grade", "Household Yearly Income (£1000)")
names(demo_names) <- demo_questions


plot_list <- lapply(demo_questions, function(var_name){
  plot_distribution(demo_data, demo_names, demo_answers, var_name)
})

ggarrange(plotlist = plot_list,
          ncol = 1, nrow = length(plot_list), align = "v")

# ggsave(here("figs", "explore_covar.pdf"), height = 6, width = 9)

```

``` {r}
plot.attitude <- ggplot(outcome.data, aes(x = Concern)) +
  geom_histogram(aes(y = ..density.., weight = weights), bins = 34, colour = 1, fill = "white") +
  geom_density(lwd = 0, colour = 4,
               fill = 4, alpha = 0.25) +
  theme_bw()
plot.action <- ggplot(outcome.data, aes(x = Action)) +
  geom_histogram(aes(y = ..density.., weight = weights), bins = 8, colour = 1, fill = "white") +
  geom_density(lwd = 0, colour = 4,
               fill = 4, alpha = 0.25) +
  theme_bw()

ggarrange(plot.attitude, plot.action,
          ncol = 2, nrow = 1, align = "hv")

# ggsave(here("figs", "explore_outcome.pdf"), height = 3, width = 6)
```

``` {r}
outcome_index <- 2

X <- as.matrix(covars.data)
ols.fit <- lm(outcome.data[, outcome_index] ~ X + 0, weights = weights)
ols.coef <- ols.fit$coefficients[!is.na(ols.fit$coefficients)]
EHW_std <- sqrt(diag(hccm(ols.fit, type = "hc1")))
tvals <- ols.coef / EHW_std
pvals <- 2 * pt(-abs(tvals), df = ols.fit$df.residual)
ols.selected <- which(pvals <= 0.005)
ols.selected <- sapply(names(ols.selected), function(name){
  substr(name, 2, nchar(name))
}) %>% unname()
print(ols.selected)

# plot2 <- ggplot(data.frame(fitted.values = ols.fit$fitted.values, residuals = ols.fit$residuals)) +
#   geom_point(aes(x = fitted.values, y = residuals), alpha = 0.1 * weights) +
#   # ylim(-1.5, 1.5) +
#   theme_bw()
# ggarrange(plot1, plot2, labels = c("Concern", "Action"),
#           ncol = 2, nrow = 1, align = "hv")
# 
# ggsave(here("figs", "fit_vs_res.pdf"), height = 3, width = 6)
```


``` {r fig.width=2, fig.height=2}
# outcome_index <- 1
set.seed(2)

lasso.cv <- cv.glmnet(x = as.matrix(covars.data), y = outcome.data[, outcome_index],
                      weights = weights, family = 'gaussian')

lambda.cv <- lasso.cv$lambda.1se

lasso.fit <- glmnet(x = as.matrix(covars.data), y = outcome.data[, outcome_index],
                    weights = weights, lambda = lambda.cv, family = 'gaussian')
lasso.selected <- which(abs(lasso.fit$beta) > mean(abs(lasso.fit$beta[abs(lasso.fit$beta) > 1e-6])))
# lasso.selected <- which.max(as.vector(abs(lasso.fit$beta)))
lasso.selected <- names(covars.data)[lasso.selected]

print(lasso.selected)

# pdf(file = here("figs", "lasso_cv2.pdf"))
# plot(lasso.cv)
# dev.off()

# ggsave(here("figs", "lasso_cv1.pdf"), height = 3, width = 3)
```

``` {r}
selected <- intersect(ols.selected, lasso.selected)
print(selected)
```

``` {r}
covars.data.org <- covars.data
outcome.data.org <- outcome.data
weights.org <- weights
n <- length(weights.org)

mc_size <- 100

sel_freq <- sapply(1:mc_size, function(mc_i){
  samples <- sample(n, ceiling(n*0.8))
  
  covars.data <- covars.data.org[samples, ]
  outcome.data <- outcome.data.org[samples, ]
  weights <- weights.org[samples]
  
  # OLS
  X <- as.matrix(covars.data)
  ols.fit <- lm(outcome.data[, outcome_index] ~ X + 0, weights = weights)
  ols.coef <- ols.fit$coefficients[!is.na(ols.fit$coefficients)]
  EHW_std <- sqrt(diag(hccm(ols.fit, type = "hc1")))
  tvals <- ols.coef / EHW_std
  pvals <- 2 * pt(-abs(tvals), df = ols.fit$df.residual)
  ols.selected <- which(pvals <= 0.005)
  ols.selected <- sapply(names(ols.selected), function(name){
    substr(name, 2, nchar(name))
  }) %>% unname()
  
  # lasso
  lasso.cv <- cv.glmnet(x = as.matrix(covars.data), y = outcome.data[, outcome_index],
                        weights = weights, family = 'gaussian')
  
  lambda.cv <- lasso.cv$lambda.1se
  
  lasso.fit <- glmnet(x = as.matrix(covars.data), y = outcome.data[, outcome_index],
                      weights = weights, lambda = lambda.cv, family = 'gaussian')
  lasso.selected <- which(abs(lasso.fit$beta) > mean(abs(lasso.fit$beta[abs(lasso.fit$beta) > 1e-6])))
  # lasso.selected <- which.max(as.vector(abs(lasso.fit$beta)))
  lasso.selected <- names(covars.data)[lasso.selected]
  
  mc.selected <- intersect(ols.selected, lasso.selected)
  return(selected %in% mc.selected)
})

sel_freq <- rowSums(sel_freq) / mc_size * 100

data.frame(covariate = selected, frequency = sel_freq) %>%
ggplot(aes(x = covariate, y = frequency)) +
  geom_bar(stat="identity") +
  geom_hline(yintercept = 50, linetype = "dashed") +
  theme_bw() +
  labs(y = "frequency (%)")

ggsave(here("figs", "robust_action.pdf"), height = 3, width = 5)

final.selected <- selected[sel_freq > 50]
```

``` {r}

plot.data <- data.frame(covar = NULL, covar_name = NULL,
                        outcome = NULL, outcome_name = NULL)
for(covar_explore in final.selected){
  plot.data <- rbind(plot.data, data.frame(covar = covars.data[[covar_explore]],
                                           covar_name = covar_explore,
                                           outcome = outcome.data[, outcome_index]))
}

ggplot(plot.data, aes(x = covar, y = outcome)) +
  geom_point(alpha = 0.1 * rep(weights, length(final.selected)), shape = 16) +
  facet_grid(. ~ covar_name) +
  ylim(-1.5, 1.5) +
  labs(y = c("Concern", "Action")[outcome_index]) +
  theme_bw()

ggsave(here("figs", "res_action.pdf"), height = 3, width = 3)
```
